name: Supabase Deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "database/**"
  pull_request:
    branches: [main]
    paths:
      - "database/**"

jobs:
  deploy:
    name: Deploy to Supabase
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database

    steps:
      - uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy dựa trên Branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            CONFIG="prd"
          else
            CONFIG="dev"
          fi

          echo "Đang lấy secrets từ config: $CONFIG"

          doppler run -p 20206205tech -c $CONFIG -- supabase link --project-ref "$SUPABASE_PROJECT_ID"
          doppler run -p 20206205tech -c $CONFIG -- supabase db push
          doppler run -p 20206205tech -c $CONFIG -- supabase migration list
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
