name: Database Keep-Alive
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./database

    steps:
      - uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: supabase migration list
        run: |
          for CONFIG in "dev" "prd"
          do
            echo "-------------------------------"
            echo "Đang chạy cho môi trường: $CONFIG"
            
            doppler run -p 20206205tech -c $CONFIG -- supabase link --project-ref "$SUPABASE_PROJECT_ID"
            doppler run -p 20206205tech -c $CONFIG -- supabase migration list
          done
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
